### ISSUE TITLE
Restart mavp2p on serial autopilot restart

### ISSUE THREAD

**Issue by Autonomost** [aler9/mavp2p#5]
Hey Alessandro. First of all, this software is awesome! Great work! 

When initiating a restart command of the autopilot from a gcs, mavp2p doesn't try to re-establish the serial connection. 
As a workaround I've created two services: one to run mavp2p and one to detect the disconnection and restart the mavp2p service. I'm not familiar with programming in go, but I'm more than happy to help get this code mod added if you're able to point me in the right direction. 

Thanks!

**Comment by aler9** [comment]
Hello, if you explain how you're able to detect disconnection of the serial port, i'd be happy to implement it into gomavlib and mavp2p.

**Comment by Autonomost** [comment]
Hey Alessandro. My way was pretty hacky, I was simply combing a simplified dmesg output and when I saw a line with 'USB disconnect' I restarted my mavp2p service. I don't have the pi on hand right now but I can post the exact code if you'd like? You might think of a better way.

**Comment by aler9** [comment]
This feature is now supported in v0.7.0.

**Comment by Autonomost** [comment]
Apologies I didn't get time to test it out. Thanks a lot!
